pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials') 
        IMAGE_NAME = "your-docker-hub-username/flask_app"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/your-GitHub-username/ansible-flask-docker.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('flask_app') {
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    sh "echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin"
                    sh "docker push $IMAGE_NAME"
                }
            }
        }
        
        stage('Trigger Ansible Deployment') {
            steps {
                sshagent(['controller-ssh-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@controller-public-ip 'ansible-playbook -vv -i inventory.ini playbook.yml --tags deploy'
                    """
                }
            }
        }
    }
}

