pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials') 
        IMAGE_NAME = "sushmitha6300/flask-app"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Sushmitha6300/ansible-flask-docker.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('flask-app') {
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    sh "echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin"
                    sh "docker push $IMAGE_NAME"
                }
            }
        }
        
        
        stage('Trigger Ansible Deployment') {
            steps {
                sshagent(['controller-ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@34.205.63.118 'ansible-playbook -i inventory.ini playbook.yml'  
                    '''
                }
            }
        }
    }
}
